backend:
  name: git-gateway
  repo: ehylam/nextjs.blog

media_folder: public/assets
public_folder: public/public_assets

collections:
  - name: 'Blog Post'
    label: 'Blog'
    folder: 'public/posts'
    create: true
    slug: '{{year}}/{{title}}'
    media_folder: ''
    public_folder: ''
    path: '{{year}}/{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
